install.packages('lattice')
install.packages("ggplot2")
install.packages("tidyverse")
install.packages("funModeling")
install.packages("Hmisc")
library('lattice')
library('ggplot2')
library('tidyverse')
library('funModeling')
library('Hmisc')
head(barley, 120)
nrow(barley)
ncol(barley)
table(barley[,'site'])
table(barley[,'variety'])
table(barley[,'year'])
names(barley)
str(barley)
summary(barley)
summary(barley$yield)
summary(barley$variety)
summary(barley$year)
summary(barley$site)

ggplot(barley, aes(x=site, y=yield)) + geom_col()
ggplot(barley, aes(x=year, y=yield)) + geom_col()
ggplot(barley, aes(x=variety, y=yield)) + geom_col()